# Generated by Django 6.0.3 on 2026-03-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False, help_text='Customer must make a selection in this group before adding to cart')),
                ('min_selections', models.PositiveSmallIntegerField(default=1, help_text='Minimum number of choices the customer must select (when required)')),
                ('max_selections', models.PositiveSmallIntegerField(default=1, help_text='Maximum choices allowed. 1 = radio buttons; >1 = checkboxes')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='restaurants.menuitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Extra cost added to the base item price when this choice is selected', max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='restaurants.optiongroup')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
