# Generated by Django 6.0.3 on 2026-03-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_optiongroup_optionchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
    ]
