# Generated by Django 6.0.3 on 2026-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_menuitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.JSONField(default=list, help_text='List of ingredients as objects: [{name, quantity, unit, notes}]'),
        ),
    ]
