# Generated by Django 6.0.3 on 2026-03-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_menuitem_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
    ]
