# Generated by Django 6.0.2 on 2026-04-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_restaurantcomment_restaurantlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='restaurantcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='restaurants.restaurantcomment'),
        ),
    ]
