# Generated by Django 6.0.3 on 2026-04-11 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postimage'),
        ('restaurants', '0018_add_lat_lng_to_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='restaurants.restaurant'),
        ),
    ]
