# Generated by Django 6.0.3 on 2026-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_notification_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_connection', 'New Connection'), ('connection_request_received', 'Connection Request Received'), ('connection_request_accepted', 'Connection Request Accepted'), ('connection_request_declined', 'Connection Request Declined'), ('plan_joined', 'Plan Joined'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented'), ('post_shared', 'Post Shared'), ('restaurant_liked', 'Restaurant Liked'), ('restaurant_commented', 'Restaurant Commented'), ('restaurant_reviewed', 'Restaurant Reviewed'), ('menu_item_liked', 'Menu Item Liked'), ('menu_item_commented', 'Menu Item Commented'), ('menu_item_shared', 'Menu Item Shared')], max_length=30),
        ),
    ]
